### ISSUE TITLE
errors flagged in the plugin folder

### ISSUE THREAD

**Issue by BluKombucha** [QoboLtd/cakephp-survey#43] opened 2018-08-14 19:34 UTC
also i have these error flagged see below:
![image](https://user-images.githubusercontent.com/16124768/44113842-70189878-9fd7-11e8-8dd6-8dccc947b55f.png)

**Comment by anvyst** [comment] 2018-08-15 09:26
@BluKombucha errors shown depend on what version of jshint/jslint your IDE is using, and what are the default rulesets defined in there.

**Comment by mamchenkov** [comment] 2018-08-15 10:30
@BluKombucha ,

thanks for the info.  As @anvyst already mentioned, this is an issue with your IDE configuration.  We use PHP CodeSniffer for testing the coding style, and we make sure that there are no errors (warnings are fine).

You can see the CodeSniffer configuration in `phpcs.xml.dist` file.  And you can run the check manually from the command line.  Here's the output from my local environment:

```
$ ./vendor/bin/phpcs 
...........W............................................S... 60 / 62 (97%)
W.                                                           62 / 62 (100%)

FILE: cakephp-survey/src/Controller/AppController.php
-----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-----------------------------------------------------------------------
 26 | WARNING | Missing @return tag in function comment
-----------------------------------------------------------------------


FILE: cakephp-survey/webroot/js/raphael-min.js
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | WARNING | File appears to be minified and cannot be processed
----------------------------------------------------------------------

Time: 1.16 secs; Memory: 10Mb
```

This check is also part of the TravisCI test runs (defined in `.travis.yml` file).

You can adjust your IDE configuration accordingly.  I'll close this issue as it's not a bug.

**Closed by mamchenkov** 2018-08-15 10:30 UTC

**Comment by BluKombucha** [comment] 2018-08-15 13:32
sounds good thank you.
