### ISSUE TITLE
plugin not loading even after updating bootstrap.php as per readme file

### ISSUE THREAD

**Issue by BluKombucha** [QoboLtd/cakephp-survey#42] opened 2018-08-14 13:40 UTC
this is what i have in my app/config/bootstrap.php:
![image](https://user-images.githubusercontent.com/16124768/44094985-a4ae1a2c-9fa5-11e8-803b-7fa1699887d5.png)

when i try to use your plugin -this is what i get:
![image](https://user-images.githubusercontent.com/16124768/44095053-ccb1b880-9fa5-11e8-9e02-d8e290591a0a.png)

is there something i need to add to my composer.json, for instance? 
the setup as you have right now on your readme is not working.
thanks.

**Comment by mamchenkov** [comment] 2018-08-14 13:58
@BluKombucha what's the URL that you are trying to access?

**Comment by BluKombucha** [comment] 2018-08-14 14:11
any url i am trying to access gives me that same error above - please look below my plugin folder structure if you can spot any issue as well:
![image](https://user-images.githubusercontent.com/16124768/44096877-569f9dd8-9faa-11e8-9124-238f99b6d2e3.png)

**Comment by BluKombucha** [comment] 2018-08-14 14:13
I've changed the  folder name because originally i thought the name of the plugin was " cakephp-survey" but after your email this morning, i see it should be "Survey", right?

**Comment by anvyst** [comment] 2018-08-14 14:14
@BluKombucha are you using CakePHP 3.x version or CakePHP 2.x?

**Comment by BluKombucha** [comment] 2018-08-14 14:15
cakephp 3x

**Comment by anvyst** [comment] 2018-08-14 14:16
@BluKombucha If you're installing plugins using composer, it should be automatically be added into `pathtoyourapp/vendor/qobo/cakephp-survey/` directory.

**Comment by BluKombucha** [comment] 2018-08-14 14:18
yes. with other plugins that's what happened but with this one it didn't.

**Comment by anvyst** [comment] 2018-08-14 14:19
@BluKombucha did composer echo'ed any errors when you tried running `composer require qobo/cakephp-survey` ? If yes - could you paste them here?

**Comment by anvyst** [comment] 2018-08-14 14:32
Try the following:
1. Rename back the directory so it would be `vendor/qobo/cakephp-survey`
2. Run `composer dump-autoload` from your application directory
3. Check `composer.lock` it should have contain information on `qobo/cakephp-survey` being installed (with all related versioning information, etc.)

It will try dumping all autoloaded classes from plugins installed via `composer` into `vendor/composer/autoload_psr4.php`

There, if the plugin was installed correctly, you'd be able to see something like this:

```
return array(
....
Qobo\\Survey\\Test\\Fixture\\' => array($vendorDir . '/qobo/cakephp-survey/tests/Fixture'),
'Qobo\\Survey\\' => array($vendorDir . '/qobo/cakephp-survey/src'),
....
);
```

**Comment by BluKombucha** [comment] 2018-08-14 14:39
ok. will try but for step 1: "Rename back the directory so it would be vendor/qobo/cakephp-survey"
which directory you're referring to - the one bellow plugins in my app?
![image](https://user-images.githubusercontent.com/16124768/44098396-25e1693e-9fae-11e8-8272-522486d04db5.png)
so it should be "cakephp-survey" (like i originally had it) instead of "Survey"?
is that correct?

**Comment by anvyst** [comment] 2018-08-14 14:47
yes, plus in CakePHP 3.5+ versions, there should be no `plugins` directory. 
The structure of the project should be something like this:

```
app/
  bin/
  config/
  logs/
  src/   <-- app's source code, your Models|Controllers|etc.
  tests/
  vendor/ <--- where composer installs all the plugins
     qobo/ <--- namespace of Qobo packages (qobo/cakephp-utils, qobo/cakephp-survey, etc.)
        cakephp-survey/ <-- actual cakephp-survey source code
     cakedc/ <-- CakeDC is another famouse contributor to CakePHP community
        users/ <-- here will be stored their plugin after `composer require cakedc/users`
```

Plus, I just noticed that you cannot install the plugin as it's stickly imposed on using `~3.5` cakephp version. If you use newer version - let me know, I'll figure something out :)

**Comment by BluKombucha** [comment] 2018-08-14 14:55
strange.  i've downloaded cakephp 3.5 for that reason to use your plugin as it originally didn't work on 3.6...?
see below:
![image](https://user-images.githubusercontent.com/16124768/44099371-7a6715d8-9fb0-11e8-8361-76df43b94cc8.png)

**Comment by anvyst** [comment] 2018-08-14 15:11
I've managed to do a clean CakePHP 3.5.0 installation on my local (non-windows) machine.
Here're the steps:

1. Installing fresh copy of CakePHP 3.5 version:
```
composer create-project --prefer-dist cakephp/app:3.5 my_app_name
```
2. Go into `my_app_name` directory

``` 
cd my_app_name
```
3. Install Qobo/Survey plugin:
```
composer require qobo/cakephp-survey
```

4. In order to work plugin should loaded:
```
./bin/cake plugin load --bootstrap --routes Qobo/Survey
```
It will add required `Plugin::load()` into `config/bootstrap.php`

5. Next we make sure that the database tables are in place:

```
./bin/cake migrations migrate --plugin Qobo/Survey
```

It will run migration files to setup required db tables for surveys.

6. Checking that everything is in place:
```
./bin/cake server
```

And try accessing http://localhost:8765/surveys/surveys/ (localhost port is default by php -s command).

Let me know if it worked on your machine :)

**Comment by BluKombucha** [comment] 2018-08-14 15:19
okay. will give it a try. just an fyi- my local machine is windows 8.1 - not sure why your version of cakephp 3.5 is different than mine- but i'll try to do a fresh install and let you know. for step 4 in your instruction i.e. In order to work plugin should loaded:- do i issue a composer command for the following:
./bin/cake plugin load --bootstrap --routes Qobo/Survey  ?

**Comment by BluKombucha** [comment] 2018-08-14 15:25
oh i get it- i got confused with your instruction because in a windows machine it is:
bin\cake  and not  ./bin/cake
let me do a clean install again

**Comment by anvyst** [comment] 2018-08-14 15:28
@BluKombucha it's Linux/BSD way, so you're right, for Windows machine it should be `bin\cake`, my bad.

**Comment by BluKombucha** [comment] 2018-08-14 16:04
np. okay i did a clean cakephp refresh on a new project. it fails at the migration command issue. is there anything i need to setup on the database side before issuing migration? see error below:
![image](https://user-images.githubusercontent.com/16124768/44103397-21d43716-9fba-11e8-86ae-fff95ab9c21b.png)

**Comment by BluKombucha** [comment] 2018-08-14 17:04
my bad. i hadn't created a database container for the migration to target. the db error is fine now- however, when i try to go to this url:http://localhost:8765/surveys/surveyquestions/add
i get this error:
![image](https://user-images.githubusercontent.com/16124768/44106391-87796ade-9fc2-11e8-8939-e6a1e1aa0054.png)

**Comment by BluKombucha** [comment] 2018-08-14 17:12
and although the main page loads fine- where are the actions on the page? none are listed:
![image](https://user-images.githubusercontent.com/16124768/44106827-ab4cb546-9fc3-11e8-8e31-5aa746da5ee4.png)

**Comment by anvyst** [comment] 2018-08-14 17:31
@BluKombucha 

Actions column is empty because Qobo uses AdminLTE theme by default and we use icon buttons to define actions.

As a simple hook, you can create following directory: `src/Template/Plugin/Qobo/Survey/Surveys/` in the application and copy `vendor/qobo/cakephp-survey/src/Template/Surveys/index.ctp` in above directory. It will allow you directly overwrite plugin's view file.

In there, you can add text to link, so it'll be shown seen in default cake layout.

Example:
```php
 <?= $this->Html->link('<i class="fa fa-pencil"></i> Edit', ['action' => 'edit', $surveyId], ['class' => 'btn btn-default', 'escape' => false]) ?>
```

**Comment by anvyst** [comment] 2018-08-14 17:38
>  when i try to go to this url:http://localhost:8765/surveys/surveyquestions/add
> i get this error:

By default most of CakePHP plugins including cakephp-survey use `DashedRoute`.
In this case your URL will look something like `/surveys/survey-questions/add`.

**Note:** that SurveysController is using `$surveyId` parameter, so you need to create a survey first in order to add a question to it. The plugin is used for systems that require authorization in the app, so you might get an error that `AuthComponent` is not enabled (aka `$this->Auth->user()` won't return you user session, if you're not logged in).

In order to make a simple and quick login form, you already have `cakedc/users` plugin installed as part of `qobo/cakephp-utils` requirement. So you can check their documentation on how to make a basic login form and authorize a user.

**Comment by BluKombucha** [comment] 2018-08-14 19:25
even with the right  survey_id- i still get this:
![image](https://user-images.githubusercontent.com/16124768/44113478-364161d0-9fd6-11e8-87b7-c31455dee0ed.png)

**Comment by BluKombucha** [comment] 2018-08-15 13:34
so what do you suggest for me to do in this case?

**Comment by BluKombucha** [comment] 2018-08-15 13:49
you also mentioned to override the plugin's view style in src/Template/Plugin/Qobo/Survey/Surveys/
but i don't see this directory in my cakephp 3.5. here is my app directory tree:
![image](https://user-images.githubusercontent.com/16124768/44151399-73e465e2-a070-11e8-8e82-bd2a56910310.png)

**Comment by anvyst** [comment] 2018-08-15 15:47
@BluKombucha above mentioned plugin template directory can be added [manually](https://book.cakephp.org/3.0/en/plugins.html#overriding-plugin-templates-from-inside-your-application).

**Comment by BluKombucha** [comment] 2018-08-15 17:09
@BluKombucha as default database engine we use MariaDB which is similar (syntactically) with MySQL. It might be an issue with the query itself.
so what do  you suggest for me to do ?- since the query was not changed on my side and the plugin is using it

**Comment by anvyst** [comment] 2018-08-16 08:09
@BluKombucha you can try upgrading your MariaDB. This plugin was designed using v10.3.8.
Plus, you can try debugging [Query object ](https://book.cakephp.org/3.0/en/orm/query-builder.html) of CakePHP, maybe it's something with your setup.

**Comment by anvyst** [comment] 2018-08-30 08:02
Closing the issue, as there were not news for 14 days..

**Closed by anvyst** 2018-08-30 08:02 UTC
Labels: bug
